### ISSUE TITLE
Database seeding

### ISSUE THREAD

**Issue by schickling** [prismagraphql/prisma#1181]
Database seeding is a standardised way to populate a service with test data. A primary design goal for Graphcool database seeding is to provide a convenient low-overhead workflow.

We support three different kinds of seeds:

- [ ] a script
- [x] data exported from existing service as described in #1299
- [x] a `.graphql` file containing one or more mutations

## File Structure

The seed file is referenced from `prisma.yml`:

```yml
service: my-demo-app

stages:
  default: dev
  dev: local
datamodel:
- database/models.graphql

# One of the below:

seed:
  import: database/seed.graphql

seed:
  import: database/backup.zip

seed:
  run: node script.js

```

Only a single seed file can be specified. If you need a more complex seed setup, you should create a script that calls other scripts.

#### Implicit seeding on first deploy

When running `gc deploy` for the first time and a seeding is configured in the `prisma.yml`, the database will be automatically seeded. This behaviour can be avoided with the following command:

```
prisma deploy --no-seed
```

## Autogenerated fake data

In the future we can provide a script that inserts fake data using [graphql-faker](https://github.com/APIs-guru/graphql-faker) 

## Prior art

This design is inspired by existing orm and migration systems:

- Orator (Python): https://orator-orm.com/
- ActiveRecord (Ruby/Rails): https://davidmles.com/seeding-database-rails/
- Eloquent (PHP/Laravel): https://laravel.com/docs/5.5/seeding

## Open questions

- [ ] Design a standard seed script
- [ ] Should we include an empty seed script by default?
