### ISSUE TITLE
Error when no `clusterSecret` is provided is misleading

### ISSUE THREAD

**Issue by nikolasburk** [prismagraphql/prisma#1800]
# Bug Report

**Current behavior**

When I'm adding a new cluster to the `~/.prisma/config.yml` that does not have _cluster security enabled_, i.e. there is no public key on it, I shouldn't have to provide a `clusterSecret` either but should be able to `prisma deploy` to the new cluster without authentication at all.

However, when I'm running `prisma deploy` and point to that new cluster, the CLI prints the following error:

```
$ prisma deploy
 ▸    Property 'clusterSecret' of cluster digital-ocean-demo in ~/.prisma/config.yml is empty.
 ▸    Please either provide a clusterSecret or run prisma local start to generate a new one. Read more here https://bit.ly/prisma-graphql-config-yml

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

I can fix this with a temporary workaround by adding _any_ private key as a `clusterSecret` to `~/.prisma/config.yml`.

**Expected behavior?**

Enable deployment without providing a `clusterSecret` for the target cluster (this would generally allow people to have insecure clusters).

**Comment by FredyC** [comment]
I've noticed this warning popping. I don't have cluster security setup enabled or I do know that I would enable it. However, after adding `clusterSecret` and then running `prisma deploy`, I am getting error.

> Could not generate token for local cluster local. error:0906D06C:PEM routines:PEM_read_bio:no start line

This is my `config.yml`

```
cloudSessionKey: >-
  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjamVnMHRkZTIzcG1jMDE1NWJra285aXM0IiwiaWF0IjoxNTIxMjI5NDg1LCJleHAiOjE1MjM4MjE0ODV9.7rGJdlRkHHFog4dyyoKM76NOifwf-d_4tYFoxyZIlHY
clusters:
  local:
    host: 'http://192.168.99.100:4466'
    clusterSecret: xxx
```

After running `prisma local start` the `clusterSecret` is gone again and warning is back :)
