### ISSUE TITLE
Unable to deploy when using `managementApiSecret`

### ISSUE THREAD

**Issue by akoenig** [prismagraphql/prisma#2271]
# Bug Report

**Current behavior**

A `prisma deploy` to an own Prisma server which has `managementApiSecret` configured fails (CLI version `1.7.1`).

**Reproduction**

_docker-compose.yml_:

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: abcdefgh
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
```

_prisma.yml_:

```yml
endpoint: http://localhost:4466
datamodel: datamodel.graphql
```

Executing ` PRISMA_MANAGEMENT_API_SECRET=abcdefgh prisma deploy` leads to:

```
Creating stage default for service default !
 ▸    Cluster secret in env var PRISMA_MANAGEMENT_API_SECRET does not match for cluster local

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

**Comment by akoenig** [comment]
Thanks @marktani for digging into this. I also figured a solution for the case above:

`~/.prisma/config.yml`:
```
clusters:
  local:
    host: http://localhost:4466
    clusterSecret: abcdefgh
```

Executing `PRISMA_MANAGEMENT_API_SECRET=abcdefgh prisma deploy` leads to a correct deployment then.

I think we should clarify in the docs, that the `clusterSecret` should reflect the `managementApiSecret` from `docker-compose.yml`. An alternative would be that the CLI does not need a `~/.prisma/config.yml` at all, but operates based on the defined environment variables / CLI arguments. This would also lead to a simpler integration into existing CI / CD workflows.
