### ISSUE TITLE
Having issues setting up graphql playground for 1.7.1

### ISSUE THREAD

**Issue by OGNeutron** [prismagraphql/prisma#2278]
I’ve been setting up 1.7+ and I’ve come into a slight problem with both I am getting this error:

```
[GraphQL error]: Message: Project not found: 'default@default', Location: undefined, Path: undefined
[Network error]: Error: Project not found: 'default@default'
```

It seem neither my project nor playground can connect to Prisma.

**Comment by marktani** [comment]
Can you provide more information to help me reproduce this? 🙂

What is your Playground version?
What steps do you follow that result in that error?
What have you already tried to work around it?

Thanks!

**Comment by OGNeutron** [comment]
Graphql-cli 2.15.11
Prisma version 1.7.1

graphqlconfig.yml

```
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  db:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4466"
      prisma: database/prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```

prisma.yml 

```
datamodel: datamodel.graphql
endpoint: http://localhost:4466
hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project db
    - graphql prepare
```

Graphql playground knows my schema, but it can not connect to my Prisma server which is up and running.
