### ISSUE TITLE
Postgres: Could not send Query(connection dead) from Psequel

### ISSUE THREAD

**Issue by mponizil** [prismagraphql/prisma#2298]
# Bug Report

**Current behavior**

1. `docker-compose up`
2. Psequel works as expected
3. `prisma deploy` (`prisma@1.7.2`)
4. I am still able to connect to the DB, but after navigating to my Schema and selecting a table, Psequel errors with "Could not send Query(connection dead)"
5. I am still able to connect and make SQL queries from `psql`

**Reproduction**

`docker-compose.yml`
```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: mymanagementsecret
        port: 4466
        databases:
          default:
            connector: postgres
            active: true
            host: db
            port: 5432
            user: root
            password: prisma
  db:
    image: postgres:9.6
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
```

`prisma.yml`
```
endpoint: http://localhost:4466/myapp/dev

secret: myappsecret

datamodel: datamodel.graphql

hooks:
  post-deploy:
    - graphql get-schema --project database
    - graphql prepare
```

Psequel Connection Details:
```
Host: 127.0.0.1
Port: 5432
User: root
Password: prisma
Database: root
```

**Expected behavior?**

Psequel shows table contents without losing the connection.

--

Now I am still pretty new to Prisma/Docker/db setup so I apologize if this is user error. My thinking is that since the issue begins after `prisma deploy`, perhaps something happens there that gets things into a funky state. Thank you!
