### ISSUE TITLE
Add flag that adds .graphqlconfig.yml for prisma init

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2336]
# Feature Request

**What feature are you missing?**

A flag like `prisma init --create-config` that creates this `.graphqlconfig.yml` file:

```yml
projects:
  prisma:
    # uncomment to use `graphql get-schema --project prisma`
    # schemaPath: prisma.graphql
    extensions:
      prisma: prisma.yml
```

That would simplify certain getting started resources, and also prevent issues like #2335.
