### ISSUE TITLE
error with v1.8 with postgres connector: `database "prisma" already exists`

### ISSUE THREAD

**Issue by alecperkey** [prismagraphql/prisma#2383]
Error seems to be related to:
```
postgres_1  | 2018-05-08 22:17:27.925 UTC [26] ERROR:  database "prisma" already exists
```

Environment (using docker-toolbox latest on windows 10)
```
user@MSI MINGW64 ~/g/prisma18
$ docker --version
Docker version 18.03.0-ce, build 0520e24302

user@MSI MINGW64 ~/g/prisma18
$ docker-compose --version
docker-compose version 1.20.1, build 5d8c71b2

user@MSI MINGW64 ~/g/prisma18
$ prisma --version
prisma/1.8.0 (windows-x64) node-v9.11.1
```
Steps to reproduce:
https://i.imgur.com/6wJiAGV.png

---
my `docker-compose.yml` ( generated with prisma init, following new [blog postgres guide for prisma 1.8](https://blog.graph.cool/prisma-now-supports-postgres-aad74ba479cb) ):

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```
