### ISSUE TITLE
Problem with graphql codegen

### ISSUE THREAD

**Issue by OGNeutron** [prismagraphql/prisma#2436]
It seems some change has happened with Graphql-cli and Prisma, when I use graphql prepare 
I get this error:

```
Property 'subscription' in type 'Prisma' is not assignable to the same property in base type 'Prisma'.
  Type 'Subscription' is not assignable to type 'SubscriptionMap'.
    Property 'notification' is incompatible with index signature.
      Type '(args: { where?: NotificationSubscriptionWhereInput; }, infoOrQuery?: string | GraphQLResolveInfo...' is not assignable to type '(args?: any, info?: string | GraphQLResolveInfo) => AsyncIterator<any> | Promise<AsyncIterator<an...'.
        Types of parameters 'infoOrQuery' and 'info' are incompatible.
          Type 'string | GraphQLResolveInfo' is not assignable to type 'string | GraphQLResolveInfo'. Two different types with this name exist, but they are unrelated.
            Type 'GraphQLResolveInfo' is not assignable to type 'string | GraphQLResolveInfo'.
              Type 'GraphQLResolveInfo' is not assignable to type 'GraphQLResolveInfo'. Two different types with this name exist, but they are unrelated.
```

I was told they aren't using graphql prepare anymore, okay, but there's no clear instructions on how to use codegen - https://github.com/OGNeutron/Prisma_main_hub

I change my graphqlconfig.yml tried adding codegen, but all I get is this:

`√ Code for project db generated to src/generated/prisma.ts`

But nothing is generated.

**Comment by divyenduz** [comment]
I am also running into this issue with the following `.graphqlconfig.yml` file

```yml
projects:
  db:
    schemaPath: generated-schema.graphql
    extensions:
      endpoints:
        default: 'http://localhost:4466/hooks'
      prisma: prisma.yml
      codegen:
        output:
          typings: generated-prisma.ts
        generator: typegen
        language: typescript
```

Looking into it.

**Comment by steve-a-jones** [comment]
@divyenduz @OGNeutron  See related issue here: https://github.com/prismagraphql/prisma-binding/issues/164

**Comment by alvis** [comment]
After hours of researching, the following finally seems working for graphql-binding/prisma-blinding 2.0.

```yaml
projects:
  app:
    schemaPath: source/schema.graphql
    extensions:
      endpoints:
        default: 'http://localhost:4000'
  database:
    schemaPath: source/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        generator: prisma-binding
        language: typescript
        output:
          binding: source/generated/prisma.ts
```

**Note: the `.graphqlconfig.yml` above is for graphql-binding/prisma-blinding 2.0 only. For 1.x, users can refer to the now completely outdated doc...**
