### ISSUE TITLE
Prisma 1.8 Host '172.19.0.2' is not allowed to connect to this MySQL server on EC2

### ISSUE THREAD

**Issue by Lotafak** [prismagraphql/prisma#2498]
# Bug Report

**Current behavior**
With such `docker-compose.yml` file
```
version: '3'

services:
  # database-server bridge
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
    restart: always
  
  # database
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  # central api
  server:
    image: node:8.111
    build: .
    ports:
      - 4000:4000
    environment:
      PRISMA_ENDPOINT: http://prisma:4466
      PRISMA_CLUSTER: local
      PRISMA_SECRET: ${PRISMA_SECRET}
      APP_SECRET: ${APP_SECRET}
    command: >
      sh -c './wait-for prisma:4466 && prisma deploy && npm start'
    restart: always

volumes:
  db:
```

I am able to run the server locally. When copying the files over to AWS EC2 server I receive this error while running `docker-compose up`

```
prisma_1  | Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
prisma_1  | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
prisma_1  | 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:18)
prisma_1  | 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:439)
prisma_1  | 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:47)
prisma_1  | 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:38)
prisma_1  | 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:218)
prisma_1  | 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:217)
prisma_1  | 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:38)
prisma_1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:239)
prisma_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1  | 	at java.lang.Thread.run(Thread.java:748)
prisma_1  | Caused by: java.sql.SQLException: Host '172.19.0.2' is not allowed to connect to this MySQL server
prisma_1  | 	at org.mariadb.jdbc.internal.com.read.ReadInitialHandShakePacket.<init>(ReadInitialHandShakePacket.java:91)
prisma_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:649)
prisma_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:402)
prisma_1  | 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
prisma_1  | 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
prisma_1  | 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
prisma_1  | 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
prisma_1  | 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma_1  | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1  | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1  | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1  | 	... 3 more
```

I'd like to highlight that server without docker was already running on the same EC2 machine. Both local and EC2 scenarios was tested when running first set of commands:
```
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker rmi $(docker images -q)
```

**Reproduction**
It's hard to reproduce since it's hosted on my EC2 instance, although I will be happy to provide more information
