### ISSUE TITLE
Prisma on kubernetes fails on new projects

### ISSUE THREAD

**Issue by terion-name** [prismagraphql/prisma#2574]
I've faced a strange issue.

Prisma (1.8 and 1.9 — the same issue) deployed on kubernetes with following config:
```
prisma
Image:
prismagraphql/prisma:1.9-beta-26
Environment variables:
PRISMA_CONFIG (prisma-configmap): 
port: 4466
# uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
# managementApiSecret: my-secret
databases:
  default:
    connector: mysql
    host: mysql-staging-mysql
    port: 3306
    user: root
    password: rP8Iz8snQlDKj
    migrations: true
```

Application container is starting, creating a new project and running migration via cluster api. Project . successfully added, migrations run, I see all this in DB.

... but server does not respond with app api. Introspection returns a single type Node, a single query and empty mutation. Until I reboot (recreate) container — after this it starts to work properly.

I assume that it is a caching problem or sort of. Any ideas what it could be and where to dig?
