### ISSUE TITLE
CLI does not detect .graphqlconfig.yaml files, only .yml

### ISSUE THREAD

**Issue by marktani** [prismagraphql/prisma#2637]
**Describe the bug**
* `prisma info` with `.graphqlconfig.yaml` does not work.
* `graphql init` creates `.graphqlconfig.yaml` file, and not `.yml`

**To Reproduce**
1. Run `prisma init`, initialize a service
2. Run `prisma deploy` to deploy
3. Run `graphql init` and enter some values. Choose `YAML` when asked.
4. In the new `.graphqlconfig.yaml` file, replace content with

```
projects:
  db:
    schemaPath: prisma.graphql
    extensions:
      prisma: prisma.yml
```

5. Run `prisma info`. Result:

```
 ▸    Couldn’t find `prisma.yml` file. Are you in the right directory?

Get in touch if you need help: https://www.prisma.io/forum/
To get more detailed output, run $ set -x DEBUG "*"
```

**Expected behavior**
`prisma` commands detect `.graphqlconfig.yaml` file as well as `.graphqlconfig.yml` file.
