### ISSUE TITLE
Renaming .graphqlconfig values induce crash of graphql codegen

### ISSUE THREAD

**Issue by Sharlaan** [prismagraphql/prisma#2802]
**Describe the bug**
I'm trying to setup clearly separated typings for each of api / database(prisma) sides, so i can pick types for my resolvers properly after ...

Here my `.graphqlconfig.yml`
```yaml
projects:

  app:
    schemaPath: src/app.schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: ${env:API_PROTOCOL}://${env:API_HOST}:${env:API_PORT}
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/api.ts

  database:
    schemaPath: src/generated/database.schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      prisma: database/database.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/database.ts

```

.... then i get this error when i try to generate the .ts files :
```sh
D:\Mes Projets\graphql-shop\api (master -> origin)
λ yarn deploy:dev
yarn run v1.7.0
$ dotenv -e .env.dev -- docker-compose -f database/docker-compose.yml up -d && dotenv -e .env.dev cross-var "wait-port $PRISMA_PORT" && prisma deploy -e .env.dev
database_prisma_1 is up-to-date
database_postgres_1 is up-to-date
Waiting for localhost:4466.
Connected!
Deploying service `shop` to stage `local` to server `local` 133ms
Service is already up to date.

post-deploy:
project database - No changes

Running graphql get-schema --project database √
{ Error: ENOENT: no such file or directory, open 'D:\Mes Projets\graphql-shop\api\src\generated\prisma.graphql'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at read (D:\Mes Projets\graphql-shop\node_modules\prisma-binding\node_modules\graphql-import\dist\index.js:10:19)
    at D:\Mes Projets\graphql-shop\node_modules\prisma-binding\node_modules\graphql-import\dist\index.js:170:43
    at Array.forEach (<anonymous>)
    at collectDefinitions (D:\Mes Projets\graphql-shop\node_modules\prisma-binding\node_modules\graphql-import\dist\index.js:164:19)
    at Object.importSchema (D:\Mes Projets\graphql-shop\node_modules\prisma-binding\node_modules\graphql-import\dist\index.js:60:14)
    at getSchemaFromInput (D:\Mes Projets\graphql-shop\node_modules\prisma-binding\dist\bin.js:113:55)
    at D:\Mes Projets\graphql-shop\node_modules\prisma-binding\dist\bin.js:80:22
    at step (D:\Mes Projets\graphql-shop\node_modules\prisma-binding\dist\bin.js:33:23)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path:
   'D:\\Mes Projets\\graphql-shop\\api\\src\\generated\\prisma.graphql' }

Running graphql codegen ×
Done in 23.88s.
```

**Expected behavior**
`src/generated/database.schema.graphql` got properly generated, but not the 2 ts files `api.ts` and `database.ts`

**Versions (please complete the following information):**
 - OS: `Windows 10`,
 - node v10.7.0
 -  "graphql": "^0.13.2",
 -  "graphql-yoga": "^1.14.12",
 -  "prisma-binding": "^2.1.1",
 -  "prisma": "^1.12.0",

Looks like `graphql codegen` can't find `src/generated/database.schema.graphql` and instead goes for the default `src/generated/prisma.graphql` ?
What am i missing ?
