### ISSUE TITLE
Subscription CREATED event not fire

### ISSUE THREAD

**Issue by MiYogurt** [prismagraphql/prisma#2819]
my docker-compose.yml

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:

```

datamodel.graphql

```
type Post {
  id: ID! @unique
  title: String!
}
```

![end](https://user-images.githubusercontent.com/10082395/43355744-4c1b59ba-9294-11e8-9a56-6214d6f89394.gif)

i have been reading docs` https://www.prisma.io/docs/reference/prisma-api/subscriptions-aey0vohche#subscribe-to-all-changes-to-all-nodes ` but not found any useful information
