### ISSUE TITLE
Cant' deploy service with service configuration that was generated via DB introspection

### ISSUE THREAD

**Issue by nikolasburk** [prismagraphql/prisma#2840]
**Describe the bug**

I'm trying to deploy a service where the data model was generated via introspection, the DB is hosted on Heroku. 

Here is my Docker Compose file for the Prisma server (was generated by `prisma init` -> `Use existing database`):

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.14
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-247-1.compute-1.amazonaws.com
            port: '5432'
            database: daanchftb1sji4
            schema: public
            user: ikijzbkoakrlql
            password: __PASSWORD__
            migrations: false
```

This is the generated data model:

```graphql
type User @pgTable(name: "User") {
  id: Int! @unique
  name: String!
}
```

This is the output when trying to deploy the service:

```bash
~/D/passive-test $ prisma deploy
Deploying service `default` to stage `default` to server `local` 82ms

Errors:

  User
    ✖ The field `id` is reserved and has to have the format: id: ID! @unique or id: UUID! @unique.

Deployment canceled. Please fix the above errors to continue deploying.
Read more about deployment errors here: https://bit.ly/prisma-force-flag
```

Here is wha the DB schema `public` looks like:

![](https://files.slack.com/files-pri/T0MQGDA3Y-FC04EQ6H0/image.png)

**To Reproduce**

1. Setup a new Postgres DB on Heroku
2. Add a `User` table with `id` and `name` (see Postico screenshot above)
3. Run `prisma init` and select `Use existing database`
4. Provide your DB connection details (afterwards the service configuration and Docker Compose file are generated)
5. Run `prisma deploy`

**Expected behavior**

I expect the Prisma service to be available on the Prisma server.
