### ISSUE TITLE
Setting schema name in `docker-compose` will break database connection (postgresql)

### ISSUE THREAD

**Issue by BenoitRanque** [prismagraphql/prisma#2866]
## Issue:
Setting the `schema` variable in `docker-compose.yml`  as per the example bellow will break prisma ability to read/write to postgresql database. Note the configuration below is not complete (only the relevant parts are shown)
```yml
services:
  prisma:
    environment:
      PRISMA_CONFIG: |
        databases:
          default:
            connector: postgres
            schema: mySchema
```
This apparently conflicts with the endpoint setting in `prisma.yml`
Given an endpoint of `http://localhost:4466/myservice/dev` prisma will create a schema `myservice$dev` and will create the relevant tables there. However reading and writing seem to take their configuration from `docker-compose.yml`, so there will be an atemp to access the `mySchema` schema.

Solution:
remove the `schema` line from `docker-compose.yml` file.
note that you cannot simply set the schema names to be equal (in this case `myservice$dev`) as `$` is a special character and will break yml
