### ISSUE TITLE
Post-deploy `graphql get-schema` doesn't generate files

### ISSUE THREAD

**Issue by niba** [prismagraphql/prisma#2877]
**Describe the bug**
I have configured my post-deploy hook to update my database schema automatically. Unfortunately, the files are not being generated. Here is my config:

```
endpoint: http://localhost:4466
datamodel: datamodel.graphql
hooks:
  post-deploy:
    - graphql get-schema -p prisma
seed:
  import: ./seed.graphql
```

and the output of `prisma deploy`

> \> prisma deploy
> Deploying service `default` to stage `default` to server `local` 111ms
> Service is already up to date.
> 
> post-deploy:
> Running graphql get-schema -p prisma √

As you can see logs show success but it's not true.

Running graphql get-schema -p prisma manually works and generates files

- OS Windows 10
- prisma/1.13.5 (windows-x64) node-v8.9.4
- prisma server 1.13

**Comment by ShunnyBunny** [comment]
Same problem here, but I dont have the codegen part, since I am assuming thats only for typescript user?

**Comment by ShunnyBunny** [comment]
I followed the guide here https://www.prisma.io/docs/develop-prisma-service/service-configuration/data-model-knul/

Under one of the section
```
.graphqlconfig.yml

project:
  db:
    schemaPath: prisma.graphql
    extensions:
      prisma: prisma.yml
```
example was given, for the longest time I could not figure out why the schema file was not generating for me. It seems that the "project" heading has to be "projects"

**Comment by tzjoke** [comment]
@niba did you find a solution? I ran into the same problem as you yesterday and haven't found a solution yet.

**Comment by niba** [comment]
@tzjoke nope, I decided to not use Prisma and graphql because Prisma doesn't support interface inheritance and unions and all of my issues that I reported have been closed by the stale bot

**Comment by evenmed** [comment]
I'm having this issue now. Prisma was working fine along with my post-deploy hook `graphql get-schema -p prisma`, but since yesterday it just doesn't update the generated file.

This is my `.graphqlconfig.yml` file:

````
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4444"
  prisma:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
````

And this is my `prisma.yml`:
````
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.prisma
secret: ${env:PRISMA_SECRET}
hooks:
  post-deploy:
    - graphql get-schema -p prisma
````

I haven't changed those files at all, nor have I changed my prisma version or anything similar.

**Comment by evenmed** [comment]
Alright I fixed it based on this answer: https://github.com/prisma/prisma/issues/3469#issuecomment-455955230

I had to change my `prisma.yml` to:

````
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.prisma
secret: ${env:PRISMA_SECRET}
generate:
  - generator: graphql-schema
    output: ./src/generated/
hooks:
  post-deploy:
    - graphql get-schema -p prisma
    - prisma generate
````
