### ISSUE TITLE
Prisma 1.13 server port is hardcoded to 9000

### ISSUE THREAD

**Issue by dijbi** [prismagraphql/prisma#2907]
Prisma 1.13 port is hard coded to 9000 and doesn't take care of the docker compose configuration. 

**To Reproduce**
1. Docker compose  with Prisma 1.13 docker image.
2. docker-compose up -d
3. docker-compose logs

Server is starting with 9000 port. Graphql playground is reachable on 9000 but not the server.

**Additional context**
Here 's below my initial post to PRISMA Forum before trying the 1.12 docker hub image.

[...]

My config 
- OS:  Ubuntu 16.04
- Docker version : 17.05.0-ce
- Docker-compose version : 1.6.1
- Docker image  prismagraphql/prisma
- Prisma CLI  version : 1.13.7 
- Node V8.8.1
- Nginx 1.10.3 for reverse proxy 
- SSL with Let's encrypt

docker-compose.yml : 
```
 version: '3'
services:
  prisma:
    image: prismagraphql/prisma
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        enableManagementApi: true
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: __SECRET__
        databases:
          default:
            connector: mysql
            host: host.docker.internal
            port: 3306
            user: root
            password: __PASS__
            migrations: true
      SQL_INTERNAL_PASSWORD: __PASS__
      SQL_INTERNAL_HOST: mysql
      SQL_INTERNAL_USER: root
      SQL_INTERNAL_DATABASE: graphcool
      SQL_INTERNAL_PORT: 3306
      SQL_CLIENT_CONNECTION_LIMIT: 10
      SQL_CLIENT_PASSWORD: __PASS__
      SQL_CLIENT_USER: root
      SQL_CLIENT_PASSWORD: __PASS__
      SQL_CLIENT_HOST: mysql
      SQL_CLIENT_PORT: 3306
      CLUSTER_ADDRESS: https://{__CLUSTER_ADDRESS__}
      SCHEMA_MANAGER_SECRET: ******
    SCHEMA_MANAGER_ENDPOINT: https://{__CLUSTER_ADDRESS__}/manager/schema
      RABBITMQ_URI: ""
      BUGSNAP_API_KEY: ""
  mysql:
    image: mysql:5.7
    restart: always
    ports :
      - 3306:3306
    environment:
      - MYSQL_DATABASE=graphcool
      - MYSQL_ROOT_PASSWORD=PASS2
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
```

Output from docker-compose logs

> prisma_1  | Obtaining exclusive agent lock...
> prisma_1  | Obtaining exclusive agent lock... Successful.
> prisma_1  | Deployment worker initialization complete.
> prisma_1  | Initializing workers...
> prisma_1  | Successfully started 1 workers.
> prisma_1  | Server running on :9000
> prisma_1  | Version is up to date.
> 

Relevant output from ipTables 

> Chain DOCKER 
> target     prot opt source               destination
> []
> ACCEPT     tcp  --  anywhere             172.22.0.2           tcp dpt:mysql
> ACCEPT     tcp  --  anywhere             172.22.0.3           tcp dpt:4466
> 

Docker ps -a output :

> 86509c7937cf        prismagraphql/prisma          "/app/bin/single-s..."   XX minutes ago      Up About a minute         0.0.0.0:4466->4466/tcp   dockerprisma_prisma_1
> 34b407e6a004        mysql:5.7                     "docker-entrypoint..."   XX minutes ago      Up About a minute         0.0.0.0:3306->3306/tcp   dockerprisma_mysql_1
> 
> 

Nginx Reverse Proxy config file : 

```
 server {
        listen 80;
        ##listen [::]:80 ipv6only=on;
        server_name {__CLUSTER_ADDRESS__};
        include /etc/nginx/snippets/letsencrypt.conf;
        location / {
         return 301 https://{__CLUSTER_ADDRESS__}$request_uri;
        }
 
 }
 
 server {
         server_name {__CLUSTER_ADDRESS__};
         listen 443 ssl http2;
         listen [::]:443 ssl http2 ipv6only=on;
 
         ssl_certificate /etc/letsencrypt/live/{__CLUSTER_ADDRESS__}/fullchain.pem;
         ssl_certificate_key /etc/letsencrypt/live/{__CLUSTER_ADDRESS__}/privkey.pem;
         ssl_trusted_certificate /etc/letsencrypt/live/{__CLUSTER_ADDRESS__}/fullchain.pem;
         include /etc/nginx/snippets/ssl.conf;
 
         location / {
 
                 proxy_set_header        Host $host;
                 proxy_set_header        X-Real-IP $remote_addr;
                 proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_set_header        X-Forwarded-Proto $scheme;
 
                 proxy_pass               http://localhost:4466;
                 proxy_redirect          http://locahost:4466/ $scheme://$host;
                proxy_http_version      1.1;
         }
 }
 
 
```
I did a simple :
Prisma init helloword && cd helloworld && prisma deploy
I used 'Other server' and put as an endpoint URL https://{__CLUSTER_ADDRESS__}, as service : Prisma, as stage : dev
so my prisma.yml is : 
 
endpoint: https://{__CLUSTER_ADDRESS__},/prisma/dev
datamodel: datamodel.graphql

-----------------------------------------------------------------------------------------------------

What's stroke me first was the port the server was running on : 9000.
Every configuration file i've read so far were : 4466. I did try to put a NODE_PORT in .env file or directly in the docker-compose file and nothing changed.
I was unable to reach the webserver at all and any curl command to the http(or https)://{__CLUSTER_ADDRESS__} gave me a 501 bad gateway error page.

The prisma container could reach the mysql container.
A netstat -a inside the prisma container gave me no '4466' port open, but a '9000' port open, connection the mysql container was ok.

So i tried to change every occurence of the 4466 port to 9000 (in nginx reverse proxy cong file, docker-compose file, i recheck iptables) and finally i could get a response for the server with a graphql playground page.

I have tried to  go to :  https://{__CLUSTER_ADDRESS__}/management and i have a nginx error  of 'no ressource can be found'. and https://{__CLUSTER_ADDRESS__}/manager/schema - i have a graphql playground page.

-----

I have tried changing the DOCKER image to 1.12, the 9000 port is gone for a 4466 (hey :smile:), the server is reachable.
 (I still have issue with prisma deploy... :()

**Comment by marktani** [comment]
I cannot reproduce this.

This is my `docker-compose.yml`:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.13
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:

```
